### PR TITLE
Add Weblate

### PR DESCRIPTION
**Pull request by Calinou**
[Weblate](https://weblate.org/) is a free web-based translation management system.

### CODE REVIEW

**Comment by caniszczyk** [comment]
Sorry this isn't interesting for open source programs.

**Comment by Calinou** [comment]
@caniszczyk Weblate is used in hundreds of open source projects. In fact, the [official hosted instance](https://hosted.weblate.org/) hosts translations for open source software exclusively (see [Hosting Weblate](https://weblate.org/en/hosting/#free)). It's also possible to self-host Weblate.

**Comment by caniszczyk** [comment]
@Calinou sorry you're correct

**Comment by caniszczyk** [comment]
https://github.com/todogroup/awesome-oss-mgmt/commit/55c4be42a6f3155c4f900c704f9e8cb8a0621f1d

**Pull request closed without merging**
