### PR TITLE
Awesome list requirements

### PR DESCRIPTION
**Pull request by jdorfman**
Checked off the following requirements¹ for a compliant Awesome™️ list

- [x] Includes the Awesome badge.
  - [x] Should be placed on the right side of the readme heading.
- [x] Has a Table of Contents section.
- [x] If you use a license badge, it should be SVG, not PNG.

¹ https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md#requirements-for-your-awesome-list

### CODE REVIEW

**Comment by jdorfman** [comment]
Not sure why 1d40b7a is failing

**Comment by jparise** [comment]
@jdorfman I'm fixing up those underlying issues in #30.

**Comment by jparise** [comment]
@jdorfman If you rebase your changes atop 485d656cdaeb6404112b13e7d34dcc8a23781d1f, you should get a clean CI build.

**Comment by jdorfman** [comment]
@jparise should I make a new PR? https://github.com/jdorfman/awesome-oss-mgmt/tree/jdorfman-awesome-rebase

**Comment by jparise** [comment]
No, you can just rebase this one and force-push it to your existing `jdorfman-awesome-requirements` branch.

**Pull request merged**
