### PR TITLE
created CONTRIBUTIONS.md

### PR DESCRIPTION
**Pull request by shanecoughlan**

### CODE REVIEW

**Comment by caniszczyk** [comment]
is this necessary?

**Comment by kpfleming** [comment]
If this is to be merged, it will need to be called CONTRIBUTING.md because that is the magic filename GitHub looks for to generate contribution notices to people.

**Comment by shanecoughlan** [comment]
Originates from discussion with Jon in #15

**Comment by shanecoughlan** [comment]
Done.

**Comment by caniszczyk** [comment]
we assume basic knowledge of using GitHub, nothing in the CONTRIBUTING.md outlines contributing guidelines imho

**Comment by jparise** [comment]
I instead propose #21 which adds a set of general contribution guidelines.

**Pull request closed without merging**
